# TP1 - SGF (groupe SR 1.1)
# ANDRIAMILANTO Tompoariniaina
# IHSINE Azzeddine

# Global vars
CFLAGS = -g -Wall


# Compilations
all: partie1 partie2

partie1: partie1.c
	gcc $(CFLAGS) -o partie1 partie1.c

partie2: partie2.c
	gcc $(CFLAGS) -o partie2 partie2.c


# Clean the workspace
clean:
	rm partie1
	rm partie2


# Test programs
test:
	./partie1