# TP3 - SGF (groupe SR 1.1)
# ANDRIAMILANTO Tompoariniaina
# IHSINE Azzeddine

# Global vars
CFLAGS = -g -Wall -lpthread -pthread


# Compilations
matmult: matmult.c
	gcc $(CFLAGS) -o matmult matmult.c


# Clean the workspace
clean:
	rm matmult
