# TP4 - SGM (groupe SR 1.1)
# ANDRIAMILANTO Tompoariniaina
# IHSINE Azzeddine

# Global vars
CFLAGS = -g -Wall


# Compilations
all: matrice

matrice: matrice.c
	gcc $(CFLAGS) -o matrice matrice.c


# Clean the workspace
clean: mrproper

mrproper:
	rm matrice